[package]
name = "a2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.27.0"
num = "0.4.1"
pathfinding = "4.6.0"
